### ISSUE TITLE
How to move the player up, down, left and right?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [CraterCrash/godot-orchestrator#109]
### Description

![2024-02-28 091559](https://github.com/Vahera/godot-orchestrator/assets/12076232/5dfb77d7-a345-4410-9e79-3470f78bad14)

I still can't find the instructions after reading the documentation, can you provide more complete documentation and examples?

**Comment by Naros** [comment]
Hi @Yakumo-Yukari there is a demo available in the https://github.com/Vahera/godot-orchestrator/releases/tag/v2.0.dev3 for each of the 3 major platforms (Linux, MacOS, and Windows), which includes a player controller.  Have you taken a look at that example that shows how to do that?

**Comment by Naros** [comment]
Hi @Yakumo-Yukari, please take a look at the godot-orchestrator-demo-v2.0-dev3.win32.zip.  This contains a sample project that has a complete character / player controller.
