### ISSUE TITLE
thanks for adding visual script to Godot 4.2

### ISSUE THREAD

**Issue by charlesmlamb** [CraterCrash/godot-orchestrator#110]
### Description

this is an amazing system, and esp. artists could benefit

going from coding text, or art takes hours, or one has to think differently

this could empower artists, or teams of creative workers, talent, or that it works for dual code content

what want to say, or that if one could customize the boxes, or to set saturation, or icons

not sure bit of customization, or that's all

#thx for this, from all the artists

### Implementation ideas

wanted to say thanks, that's all

visual coder, now more productive, etc

**Comment by Zomphie** [comment]
Hi! Thank you for your positive feedback. We will look more into this and see what we can do.

**Comment by Naros** [comment]
Hi @charlesmlamb, there are some customizations in the `Project Settings -> Orchestrator -> UI` section in the editor.  There is also an open PR to add custom border-radius for the boxes, what exactly are you looking for with saturation and icons?

**Comment by Naros** [comment]
Hi @charlesmlamb, we can certainly look into what can be done.  We could add the ability to define an alpha channel on the color palettes for backgrounds and pins/connections that you can configure in the Project Settings, allowing you to get a more saturated look with color if that would help.  

As for a greyscale mode, this sounds more like a theme-centric setting similar to `Editor Settings > Theme > Preset.`  Maybe we can have a similar drop-down with a few choices like `Gray`, `Use Editor Theme`, and `Use Orchestrator Colors`.  Would something along those lines be what you're looking for?

**Comment by charlesmlamb** [comment]
that'd be ultra - cool, get the Godot grey

very cool :-)

**Comment by Naros** [comment]
Hi @charlesmlamb and @jakobbouchard, I'm curious with the latest dev3 build with the customizations in Project Settings, is there anything specific that is missing beyond the icon customizations?
