### ISSUE TITLE
Massive header on docs pages takes up precious space

### ISSUE THREAD

**Issue by ZeikJT** [CraterCrash/godot-orchestrator#140]
### Description

I get that you want visual cohesion and for the docs to maybe look like https://forums.vahera.com/ but the doc pages don't even let you scroll the header off screen like the forums do so for me it always takes up 1/5 of the space and is just blank? Here's what I see here for example https://www.vahera.com/docs/orchestrator/2.0.0/overview.html
<img width="1728" alt="Screenshot 2024-03-07 at 5 18 49 PM" src="https://github.com/Vahera/godot-orchestrator/assets/1537686/19b67661-88c6-4cc6-a0ab-e179357b1043">

I edited the page to get rid of all that wasted space and it feels so much nicer and less claustrophobic.
<img width="1728" alt="Screenshot 2024-03-07 at 5 19 46 PM" src="https://github.com/Vahera/godot-orchestrator/assets/1537686/90ccc1dc-7d40-40c4-8ccb-82e842f49e06">

### Implementation ideas

I think it would make a huge difference to make it scroll off-screen like the forums do or better yet imo just remove it, or find some other even better fix, cheers :)

**Comment by Naros** [comment]
Hi @ZeikJT, we removed the banner and replaced it with a much smaller menu/logo pair while updating some fonts and other things to make it look a bit more crisp and professional.  Can you take a look and let us know what you think?
