### ISSUE TITLE
Lines not showing if comments isn't transparent

### ISSUE THREAD

**Issue by GhostNr1** [CraterCrash/godot-orchestrator#174]
### Describe the bug

The comments are to high in z-index so it will not show the lines if you don't use transparency on it.
![image](https://github.com/Vahera/godot-orchestrator/assets/9337875/f23f0866-f2af-411b-bf12-37690566f520)

### How to Reproduce?

1. Create some boxes and connect them
2. Create a comment that will go under the boxes
3. Set the comment to use no transparency

### Godot full version

4.2.1.stable

### Orchestrator version

v2.0.rc1

**Comment by Naros** [comment]
I think the upcoming `GraphFrame` feature will help with this from base Godot:
https://github.com/Vahera/godot-orchestrator/assets/3255568/1ad87efe-110e-4faf-904c-b596be87ece8

**Comment by GhostNr1** [comment]
That look awesome, would help a lot to organize things

**Comment by Naros** [comment]
Hi @GhostNr1, sorry this took a bit longer than I had expected, but the changes needed for the Knot operations highlighted some things we could improve upon which fixes your issue:

![image](https://github.com/user-attachments/assets/9da2c0fd-9fbc-4776-aff2-3a20b1027445)
