### ISSUE TITLE
Show Node related Inspector when click in Scene Tree

### ISSUE THREAD

**Issue by neilfranci** [CraterCrash/godot-orchestrator#436]
### Describe the bug

Click Node in Scene should show Node Inspector Property like in the video, not the .os function or anything related

I've to click another node and click back the node I want, to see the right inspector.

Like in the video, if I'm in the .os script playing around with function and stuff. Then I want to quickly check the Panel property or Node Signal tab I've to click another node and then click back the Panel to show the Panel inspector and Node-related tab.

### Expected behavior

Whenever I click the Node while in Orchestrator mode it should show that Node Inspector Property.

### Actual behavior

When I click the Node while in the Orchestrator mode, it doesn't do anything.

### How to Reproduce?

https://github.com/Vahera/godot-orchestrator/assets/66520542/c63f4344-908e-47d0-b0d9-e3f51b14c601

### Godot full version

4.3.beta2

### Orchestrator version

build from PR https://github.com/Vahera/godot-orchestrator/pull/435

**Comment by Naros** [comment]
Hi @neilfranci, thanks for the report.  

The `SceneTreeDock` is a control managed by the Godot Editor, so this needs to be changed in the upstream engine repository and not in Orchestrator.  Looking at the editor source, this should already work as you wanted as the `Tree` reselect signal is enabled; however, it does not seem the editor works this way and requires some internal changes.

According to the Godot developers, this should be possible, but it seems a longstanding bug.  Please raise a GitHub issue in https://github.com/godotengine/godot repository for this.  Thanks.

**Comment by Naros** [comment]
Just tested this against Godot 4.3.stable and it seems Godot has fixed this.
If this is still an issue, please open an issue in the upstream Godot repository.
