### ISSUE TITLE
Add possibility to save `.os` files as `.tos`

### ISSUE THREAD

**Issue by dschiller** [CraterCrash/godot-orchestrator#710]
### Description

In order to better work with version control like Git it would be handy to save Orchestrator files as `.tos`  files which are human readable. That way version control software can track changes in the Orchestrator files.

**Comment by dschiller** [comment]
Is this related to the Text *Storage Format* setting ?

![image](https://github.com/user-attachments/assets/2c9d76f3-9aac-4f2e-ac4b-7be95350d587)

Which still saves as binary:

![image](https://github.com/user-attachments/assets/3816f3e0-8da5-43f5-b9dc-1d87b82a7306)

**Comment by Naros** [comment]
It is, there are `.torch` and `.os` files.  By default in Orchestrator 2 it used `.os` (binary).  In Orchestrator 2.1, it uses `.torch` (text) by default.  So this should already be possible to re-save a `.os` to `.torch` if you want to use text-format moving forward.

**Comment by dschiller** [comment]
Yes, i need to recreate my `.os` files to the new `.torch` format to make them text based.
