### ISSUE TITLE
`Ctrl+x` does not work in EventGraph

### ISSUE THREAD

**Issue by dschiller** [CraterCrash/godot-orchestrator#714]
### Describe the bug

Removing nodes inside a EventGraph via `Ctrl+x` does not work.

### Expected behavior

`Ctrl+x` should work inside a EventGraph whit a selected node.

### Actual behavior

`Ctrl+x` does not remove the selected node inside a EventGraph. Or when an item in the Scene Dock was selected before focusing the EventGraph then this item will be removed - more worse then doing nothing.

### How to Reproduce?

1. Inside a EventGraph create a node
2. Select the node
3. Press `Ctrl+x` >> Nothing happens

### Godot full version

4.2.2

### Orchestrator version

2.0.1

**Comment by Naros** [comment]
So it does not seem that Godot's standard `GraphEdit` reacts to the `ui_cut` action, so we probably should submit an upstream PR to add this to the `GraphEdit` base control, and meanwhile we can add a hook for this in our custom class until Godot adds it upstream.

**Comment by Naros** [comment]
Added upstream PR - https://github.com/godotengine/godot/pull/95614
