### ISSUE TITLE
Make Nodes inside EventGraph movable via arrow keys

### ISSUE THREAD

**Issue by dschiller** [CraterCrash/godot-orchestrator#716]
### Description

Inside the EventGraph it becomes handy to move Nodes via the arrow keys on the keyboard. Currently the arrow keys navigate trough the Godot UI when used.

### Implementation ideas

When the EventGraph is focused selected Nodes should move corresponding to the pressed arrow keys on the keyboard.

**Comment by Naros** [comment]
So I got a small mock-up of this working; however, as you point out, the arrow keys navigate through the UI, and this happens even when I react to the events in the API, so something is most definitely not working as expected with Input in this case.  I've opened a question with the Godot devs, let's see what their response is.

**Comment by dschiller** [comment]
Wow, that was fast! It’s great to hear the mock-up working. When handling API events, you might need to invalidate the event after processing the EventGraph Node movements to prevent the events from bubbling up to Godot's UI. I've used this technique before in Python with PyQt and in JavaScript as well.

In PyQt, you can stop an event from propagating further by calling `event.accept()` or `event.ignore()`.  In JavaScript, you can stop event bubbling using `event.stopPropagation()` or `event.stopImmediatePropagation()`. Of course i am not aware of the Godot API as well how it works in C++. But maybe there is something similar in Godot's API.

**Comment by dschiller** [comment]
Tested with the main branch at https://github.com/Naros/godot-orchestrator. Knots are not moving with keys.

![Screenshot from 2024-08-13 00-56-48](https://github.com/user-attachments/assets/86de17d2-6474-4752-aea9-aecc0beeb1c8)

![Screenshot from 2024-08-13 00-57-07](https://github.com/user-attachments/assets/53db66ad-f373-45f4-a8c7-7d9d21ea617b)

**Comment by Naros** [comment]
Ah, good point, I only scoped the move to graph nodes. Let  me see how complicated adding knots will be since they work ever so slightly different.

**Comment by Naros** [comment]
Ok fixed.

**Comment by dschiller** [comment]
i am very impressed how fast you implement and fix things in Orchestrator!
