### ISSUE TITLE
Seems SSL certificate is not working properly

### ISSUE THREAD

**Issue by dschiller** [CraterCrash/godot-orchestrator#717]
### Describe the bug

When opening the CraterCrash website i see a SSL error.

![image](https://github.com/user-attachments/assets/f836510a-db1c-4f32-a240-a14cac8d872d)

The url is: https://www.cratercrash.com/orchestrator

![image](https://github.com/user-attachments/assets/2e8e4798-4a2a-49f4-857d-15c815c7722f)

### Expected behavior

The url should open w/o SSL errors

### Actual behavior

The url opens with an SSL error.

### How to Reproduce?

1. Open url https://www.cratercrash.com/orchestrator >> See invalid SSL certificate

### Godot full version

n/a

### Orchestrator version

n/a

### Additional information

Possibly the url on Github need to change from:

```
https://www.cratercrash.com/orchestrator
```

to:

```
https://cratercrash.com/orchestrator
```

**Comment by Naros** [comment]
Fixed, thanks for the report 👍
