### ISSUE TITLE
Make Variable Description visible in Node's Tooltip

### ISSUE THREAD

**Issue by dschiller** [CraterCrash/godot-orchestrator#718]
### Description

It would be handy to see a variable node's description when hovering the node.

![image](https://github.com/user-attachments/assets/658b583d-4bef-422c-ab8d-13f7814745ca)

**Comment by Naros** [comment]
I believe this is already available in 2.1.rc4 and 2.0.2.rc3.  Can you please confirm @dschiller ?

**Comment by dschiller** [comment]
Hey Chris, it seems it's not available in 2.1.rc4:

![image](https://github.com/user-attachments/assets/47958c9d-d600-4fba-aa5b-097f5b578fad)
