### ISSUE TITLE
Knots jump when moved if grid snapping is disabled

### ISSUE THREAD

**Issue by dschiller** [CraterCrash/godot-orchestrator#719]
### Describe the bug

Knots should not jump when drag start happens when the grid snapping is disabled.

### Expected behavior

Knots do not jump when grid snapping is disabled.

### Actual behavior

Knots jump when starting to move and grid snapping is disabled.

### How to Reproduce?

1. In a EventGraph create two nodes
2. Connect the Nodes
3. Hold `Ctrl` key and click the connection line >> A new Knot is created
4. Disable grid snapping in the EventGraph Toolbar
5. Click the Knot and slowly start to drag it >> you will see a small offset jump for the Knot's position

### Godot full version

4.3.rc3

### Orchestrator version

2.1.rc4

**Comment by Naros** [comment]
Yep, looking at the logic in `OrchestratorGraphKnot::set_knot` we certainly do ignore whether snapping is enabled or not.
