### ISSUE TITLE
Add option to disable Hints

### ISSUE THREAD

**Issue by dschiller** [CraterCrash/godot-orchestrator#720]
### Description

There is a new "Knot" hint in the EventGraph. Add an option to disable Hints - once read there is no need to see the Hint again when hovering Connections.

![image](https://github.com/user-attachments/assets/6c2c8804-f6dd-4131-abd1-36a193c9a52c)

**Comment by Naros** [comment]
This should already exist in `Orchestrator > UI > Graph` section, maybe the name is not very descriptive?

![image](https://github.com/user-attachments/assets/b8b6ce49-4f15-4389-b0be-f0fc1fcca30d)

**Comment by dschiller** [comment]
Perfect. Sorry for the Noise. Couldn't create the connection between the "Hints" and "Overlay Tooltips", but knowing it now makes total sense.
