### ISSUE TITLE
Copying Variables crashes Godot

### ISSUE THREAD

**Issue by dschiller** [CraterCrash/godot-orchestrator#724]
### Describe the bug

When copying Variable Nodes from one EventGraph to another then Godot crashes.

### Expected behavior

**A)** The Variable will be created in the Orchestrator Inspector's Variables Section and the Node pasted
**B)** A Message like for Events "*There are some nodes that cannot be copied, they were not placed on the clipboard.*"

### Actual behavior

When pasting a Variable in a EventGraph that does not have this Variable Godot Crashes.

### How to Reproduce?

1. Create a new Variable in a EventGraph (`float`)
2. Drag the Variable into the EventGraph and select `Set <variable>`
3. Copy this new Node via `Ctrl+c`
4. Create a new EventGraph (**a new file which does not have this Variable in the Component Panels**)
5. Paste the copied Node via `Ctrl+p` >> Godot crashes

### Godot full version

4.3.rc3

### Orchestrator version

2.1.rc4

**Comment by Naros** [comment]
Hi @dschiller what is the variable's type by chance?  I haven't been able to reproduce the crash, unfortunately.

**Comment by dschiller** [comment]
The type is `float`.

**Comment by Naros** [comment]
> The type is `float`. Also happens with type `Any` and `Array`. Did not test all Types but i believe it may fail with all types. Which type worked for you and did not crash Godot ?

I tried `Any`, `Object`, and `int` types.  I'll rollback to 2.1.rc4 explicitly and re-test but I don't think I've made any changes that would have fixed this necessarily, but maybe 🤷‍♂️ I'll check after I wrap up the merges for tomorrow's release.

**Comment by dschiller** [comment]
I compiled your main branch at https://github.com/Naros/godot-orchestrator and also see crashes when using a Variable eg. of type `int`.

**Comment by Naros** [comment]
Since I can't post a video here more than 10mb, I've started a discussion on our discord about this in #bug-reports.

**Comment by dschiller** [comment]
i can reproduce this bug on Windows 1, Linux Mint 22 and macOS Sonoma 14.5 on M1.

**Comment by dschiller** [comment]
This is the macOS Crashlog.

[Godot-2024-08-13-073307.ips.zip](https://github.com/user-attachments/files/16594808/Godot-2024-08-13-073307.ips.zip)

**Comment by dschiller** [comment]
This is the Linux Crashlog.
https://drive.google.com/file/d/1LhTYcEAuL7oJxyXExdXReiw4QkLPbi7V/view?usp=sharing

**Comment by dschiller** [comment]
> Since I can't post a video here more than 10mb

You can use VLC to resize movies:
- Install VLC
- Open VLC
- Open Menu / `Media` / `Convert / Save` (`Ctrl+r`)
- Click `Add`
- Select your movie
- Click `Convert / Save`
- In 'Settings' / `Profile` dropdown select `Video - H.264 + MP3 (MP4)`
- Click `Edit selected Profile` (Wrench icon button next to the dropdown)
- Click Tab `Video codec`
- On Tab `Encoding parameters` set `Bitrate` to `100 kb/s` (Depends on your origin bitrate, try different rates until the file gets smaller)
- Or you can change the `Scale` value on the `Resolution` Tab (eg. `0.5` or `0.75`)
- Click `Save`
- Click `Destination` / `Browse`
- Set your folder and file name
- Click `Start`
