### ISSUE TITLE
Updating to version 2.1 causes Godot to fail to start

### ISSUE THREAD

**Issue by jxaytl13** [CraterCrash/godot-orchestrator#760]
### Describe the bug

Godot4.3 version is updated from Orchestrator2.0 to Orchestrator2.1. After completion, you will be prompted to restart godot. godot will not start after restarting. Delete Orchestrator2.1 in the project file.

### Actual behavior

Open godot4.3.
Update the original Orchestrator2.0 to 2.1.
Prompt to restart godot.
Godot will not be able to start normally after restarting, causing a crash.

### Godot full version

4.3

### Orchestrator version

2.1

**Comment by Naros** [comment]
Hi @jxaytl13, please open a blank project in Godot, click `Help > About Godot` and at the top of the dialog, click the line that reads "Godot Engine..." and paste the text it puts on the clipboard here, please.

i.e.
```
v4.4.dev.custom_build [8691da0f2]
```

**Comment by jxaytl13** [comment]
> 你好@jxaytl13，请在 Godot 中打开一个空白项目，单击，`Help > About Godot`然后在对话框顶部单击“Godot Engine...”行，然后将其放在剪贴板上的文本粘贴到这里。
> 
> IE IE浏览器
> 
> ```
> v4.4.dev.custom_build [8691da0f2]
> ```
hello：
v4.3.stable.official [77dcf97d8]

**Comment by Naros** [comment]
Thanks @jxaytl13.  Are you using a custom theme in the editor?  What is your operating system?

**Comment by jxaytl13** [comment]
> 谢谢@jxaytl13。您在编辑器中使用自定义主题吗？您的操作系统是什么？

No custom theme is used, Godot's default one is used.
My operating system is wind 10
Orchestrator is updated from version 2.0 to 2.1

**Comment by Naros** [comment]
Hmm, and the crash happens even in an empty project where you update Orchestrator from 2.0 to 2.1?

**Comment by jxaytl13** [comment]
> 嗯，即使在空项目中将 Orchestrator 从 2.0 更新到 2.1 也会发生崩溃吗？

yes

**Comment by Naros** [comment]
After you have updated to 2.1, can you open a `cmd` window and navigate to where your Godot executable is, and there will be a second executable there named something like `Godot_v4.3.blah.blah.console.exe`, can you run the console version and see if it outputs any meaningful details about the crash?

**Comment by Naros** [comment]
One final question, is this Godot one you installed from Steam from the official Godot website?

**Comment by jxaytl13** [comment]
> 最后一个问题，这个 Godot 是你从 Steam 上的 Godot 官方网站安装的吗？

It's not from steam, it's downloaded from Godot official website.

**Comment by jxaytl13** [comment]
Will Orchestrator's nodes be translated into Chinese in the future? Like UE's blueprint.

**Comment by Naros** [comment]
> After you have updated to 2.1, can you open a `cmd` window and navigate to where your Godot executable is, and there will be a second executable there named something like `Godot_v4.3.blah.blah.console.exe`, can you run the console version and see if it outputs any meaningful details about the crash?

Can you perform this for me?

> Will Orchestrator's nodes be translated into Chinese in the future? Like UE's blueprint.

Yes, though I cannot give a specific version when that will be added, but its something we want to add.  We intend to do it similar to Godot with weblate & allow users to add translations that will get built into the plug-in automatically.

**Comment by jxaytl13** [comment]
> 更新到 2.1 后，您可以打开一个`cmd`窗口并导航到您的 Godot 可执行文件所在的位置，并且那里会有第二个可执行文件，名称类似于`Godot_v4.3.blah.blah.console.exe`，您可以运行控制台版本并查看它是否输出有关崩溃的任何有意义的详细信息吗？

![zz](https://github.com/user-attachments/assets/af5dc960-2ea0-486c-b3b4-f7adfbcae791)

**Comment by Naros** [comment]
What happens if you set Godot to use English rather than Chinese, does it work?  I'm wondering if Godot is translating some node names we are specifically looking for and that you could be facing a dereference problem because we expect to get the node back.

**Comment by jxaytl13** [comment]
> 如果您将 Godot 设置为使用英语而不是中文，会发生什么情况？它会起作用吗？我想知道 Godot 是否正在翻译我们专门寻找的一些节点名称，并且您可能会面临取消引用的问题，因为我们希望取回节点。
> 
> 尽管我搜索了代码，并且所有`find_children`调用都受到空指针检查的保护🤔

我试试

**Comment by Naros** [comment]
Did that work?

**Comment by Naros** [comment]
I tried with Orchestrator 2.1.stable locally with `zh_CN` language and it works, so I'm not really sure why it crashes for you.  We mostly develop on Windows 11 and Fedora here.  I'm guessing that if you download the 2.1.stable release from GitHub [here](https://github.com/CraterCrash/godot-orchestrator/releases/download/v2.1.stable/godot-orchestrator-v2.1-stable-plugin.zip) and install it manually you have the same problem?

**Comment by jxaytl13** [comment]
> I tried with Orchestrator 2.1.stable locally with `zh_CN` language and it works, so I'm not really sure why it crashes for you. We mostly develop on Windows 11 and Fedora here. I'm guessing that if you download the 2.1.stable release from GitHub [here](https://github.com/CraterCrash/godot-orchestrator/releases/download/v2.1.stable/godot-orchestrator-v2.1-stable-plugin.zip) and install it manually you have the same problem?

Downloads from github crash all the same

**Comment by jxaytl13** [comment]
Does it have anything to do with the choice I made when I created it?
![screenshot-20240818-111103](https://github.com/user-attachments/assets/af769241-3988-458b-ba61-5906121c38a5)

**Comment by jxaytl13** [comment]
> Does it have anything to do with the choice I made when I created it? ![screenshot-20240818-111103](https://private-user-images.githubusercontent.com/12883605/358880724-af769241-3988-458b-ba61-5906121c38a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NTEwMDcsIm5iZiI6MTcyMzk1MDcwNywicGF0aCI6Ii8xMjg4MzYwNS8zNTg4ODA3MjQtYWY3NjkyNDEtMzk4OC00NThiLWJhNjEtNTkwNjEyMWMzOGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDAzMTE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwZDM1Yzc2MTAwM2Y2OTI5MDVhNzc3M2UyMzQ5OTQ2NjM4MjJlNTc1MDlhYWI1OTQ0ZjkyNmRjNzhhMzU1ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GfrnejNZi-o3-nGvqaAHM9EPG5-kb270OTMGE3AJ9So)

Tried replacing it with something else, still the same.

**Comment by Naros** [comment]
No that render type doesn't matter, are you able to join our discord, so I can share a debug build with you?
https://discord.gg/J3UWtzWSkT

**Comment by jxaytl13** [comment]
> No that render type doesn't matter, are you able to join our discord, so I can share a debug build with you? https://discord.gg/J3UWtzWSkT

I'll try again when the version on AssetLib is 2.1.

**Comment by jxaytl13** [comment]
I have a question. I really like Orchestrator and would like to use it as my main tool in the future. However, I'm worried that since it's not official, it might be abandoned by its author later on. I'm hesitating between using GD (Godot's built-in scripting language) and Orchestrator.

**Comment by Jompschz** [comment]
Yes I've the same issue, my project doesn't start :0

**Comment by Naros** [comment]
What happens if you re-install the latest Microsoft C++ Redistributable?

**Comment by Jompschz** [comment]
> What happens if you re-install the latest Microsoft C++ Redistributable?

yes this solve the problem. now works!!! :D

**Comment by Naros** [comment]
> UPDATE: on a new project not works :0

I would double check that in both projects you are using the same version of the addon.  I did check the GitHub `windows-latest` runners and as of 2024/08/24 they are deployed with Microsoft Visual C++ Redistributable version 14.40.33810.

This information is available [here](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#microsoft-visual-c) on GitHub and is updated by GitHub periodically.

**Comment by Naros** [comment]
Hi @Jompschz is everything good?

**Comment by Naros** [comment]
Feel free to re-open if updating the Microsoft Visual C++ Redistributable doesn't help.
