### ISSUE TITLE
Reroute nodes

### ISSUE THREAD

**Issue by Shadowblitz16** [CraterCrash/godot-orchestrator#777]
### Description

Can we have bot named and unnamed Reroute nodes like unreal engine?

### Implementation ideas

Maybe middle clicking on a line can make a reroute node

**Comment by Shadowblitz16** [comment]
https://github.com/CraterCrash/godot-orchestrator/issues/709

**Comment by Naros** [comment]
Right now, the current reroute (aka knot) nodes you have in 2.0.2.stable and 2.1.stable are not full-fledged nodes, but instead are a collection of points assigned to a connection wire to draw the connection in a more visual appealing way. 

We've gotten feedback that users would like to see an implementation closer to UE, so we are investigating that as potentially part of 2.2 and perhaps backported to 2.1 and 2.0.
